version: '3.9'

services:

  # The application
  app:
    build:
      context: .
    image: &recipe_book recipe_book 
    ports:
      - 8000:8000
    volumes:
      - ./recipe_book:/recipe_book
    env_file:
      - .env
    command: >
      sh -c 'watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- python manage.py runserver 0.0.0.0:8000'
    links:
      - db
    depends_on:
      - db

  # Database
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5332:5332
